### ISSUE TITLE
Not listed as ready for Nuxt3 on the module page

### ISSUE THREAD

**Issue by kissu** [nuxt-modules/device#127]
Small thing IMO but the module is not listed as compatible with Nuxt3 as of right now

https://nuxt.com/modules?q=device&version=3.x

**Comment by dotneet** [comment]
Thank you.
I've submitted the PR.
https://github.com/nuxt/modules/pull/532

**Comment by CaptainFalcon92** [comment]
Hello

But is it ?

Today on December 2023, installing  @nuxtjs/device break the whole app with a message :

```
 ERROR  error while updating dependencies:                                                                                                                                    10:35:31 PM
Error: Build failed with 1 error:
node_modules/@nuxtjs/device/dist/runtime/composables/useDevice.mjs:1:27: ERROR: Could not resolve "#app"
```
