### ISSUE TITLE
Using with conditional classes

### ISSUE THREAD

**Issue by makerovski** [nuxt-modules/device#128]
Hi guys ...

I am trying to use this feature to determine CSS classes, but I could not make it work:

`    <div :class="['has-text-white', { 'has-text-warning' : $device.isDesktop }]">
     test
    </div>`
   
   This logic works as it should:
   
   `<div v-if="$device.isDesktop">
      Desktop
    </div>
    <div v-else-if="$device.isTablet">
      Tablet
    </div>
    <div v-else>
      Mobile
    </div>`
 
 I am missing something? Or is not possible to use this module to determine dynamic CSS classes?
 
 Thank you very much!

**Comment by gregmulvaney** [comment]
This looks more like an issue with your syntax. `has-text-white` is going to override your conditional class. 

`<div :class="[{ 'text-red': $device.isDesktop, 'text-white': !$device.isDesktop }]">
      test
    </div>`
This example working as expected with obvious class name changes.

**Comment by makerovski** [comment]
Hello..

Thank you very much!! I figured this error and solved some weeks ago, it works perfectly.
