### ISSUE TITLE
Does anyone ever encountered this error report " No exports main defined ..."

### ISSUE THREAD

**Issue by pangyongsheng** [nuxt-modules/device#137]
"@nuxtjs/device": "^3.1.0",
 "cross-env": "^7.0.3",
  "nuxt": "3.0.0",
 "unplugin-element-plus": "^0.4.1"

when i using yarn add  @nuxtjs/device , report errors：

 No "exports" main defined in /Users/pangyongsheng/Desktop/work/jiaoyanyun_home/node_modules/@nuxt/kit/package.json

**Comment by danielroe** [comment]
This should be resolved in the latest version of `@nuxt/kit`.
