### ISSUE TITLE
Cannot read properties of undefined (reading 'isDesktop')

### ISSUE THREAD

**Issue by pit07** [nuxt-modules/device#139]
Hi!

On Nuxt 2, I install the package

`npm install -D @nuxtjs/device`

I added '@nuxtjs/device', on the buildModules array (nuxt.config.js)

I just added this code to my page:

```
<div v-if="$device.isDesktop">
      Desktop
</div>
<div v-else-if="$device.isTablet">
      Tablet
</div>
<div v-else>
      Mobile
</div>
```

And i have an error:
**Cannot read properties of undefined (reading 'isDesktop')**

Any ideas?
Thanks!

**Comment by deevanych** [comment]
@pit07 hi! for nuxt v2 you should use `npm i @nuxtjs/device@^2.1.0 -D`
