### ISSUE TITLE
caught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@nuxtjs+device@3.1.0/node_modules/@nuxtjs/device/dist/runtime/composables/useDevice.d.ts' does not provide an export named 'default' (

### ISSUE THREAD

**Issue by parsagholipour** [nuxt-modules/device#140]
I'm getting this error on nuxt 3.4.2
Any solution?

`
caught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@nuxtjs+device@3.1.0/node_modules/@nuxtjs/device/dist/runtime/composables/useDevice.d.ts?v=2806ccb0' does not provide an export named 'default'
`

**Comment by windsora1998** [comment]
This error in nuxt 3.4.2 but nuxt 3.4.1 not have problem

**Comment by zc1342303** [comment]
Same as me.

**Comment by frontwero** [comment]
Have the same problem with Nuxt 3.6.5

**Comment by jamieowen** [comment]
Same issue... Nuxt 3.6.5 and 3.7. and 3.4.1 ( as mentioned above )
