### ISSUE TITLE
🐞 `useDevice` composable doesn't return reactive value

### ISSUE THREAD

**Issue by jd-solanki** [nuxt-modules/device#170]
Even if we write `refreshOnResize` to `true`, `useDevice` composable doesn't return reactive value and doesn't change on window resize

**Comment by elzodxon** [comment]
the same issue(

**Comment by samasarin** [comment]
Same issue

**Comment by DamianGlowala** [comment]
Closing as this module does not take viewport width into account and relies solely on the user-agent header. Read more in https://github.com/nuxt-modules/device/issues/176#issuecomment-2104091087.
