### ISSUE TITLE
 Name `$device` not found

### ISSUE THREAD

**Issue by lxccc812** [nuxt-modules/device#171]
How to use `$device` in nuxt

__VLS_ctx.$device" is of type "Unknown

![image](https://github.com/nuxt-modules/device/assets/110974969/dee1ed2b-7fa8-42ff-83d7-1becb2406012)

[docs](https://nuxt.com/modules/device#usage)

nuxt 3.7.4
@nuxtjs/device 3.1.0
chrome 118.0.5993.89

nuxt.config.ts
```
{
    modules: ['@nuxtjs/device'],
    device: {
        refreshOnResize: true
    }
}

```

**Comment by thomasjonas** [comment]
Same problem here!

**Comment by lxccc812** [comment]
When to resolve changes or documentation🤔

**Comment by DamianGlowala** [comment]
Let's track in https://github.com/nuxt-modules/device/issues/136.
