### ISSUE TITLE
how to change a layout dynamically?

### ISSUE THREAD

**Issue by durbanitas** [nuxt-modules/device#175]
I need help using this line [mentioned in the documentation](https://github.com/nuxt-modules/device#change-a-layout-dynamically) on how to change a layout dynamically:

```js
export default {
  layout: (ctx) => ctx.$device.isMobile ? 'mobile' : 'default'
}
```
### index.vue

```html
<script setup>
definePageMeta({
  layout: (ctx) => (ctx.$device.isMobile ? 'mobile' : 'default'),
});
</script>

<template>
  <main>
    ...
  </main>
</template>
```

### Error

> vite_ssr_import_6.default[props.name] is not a function

> Invalid layout `(ctx) => (ctx.$device.isMobile ? 'mobile' : 'default')` selected.
> [Vue warn]: Invalid prop: type check failed for prop "name". Expected String | Boolean, got Function

## Question

Where do I place this? My guess is initalizing as a plugin or to create a middleware...

## Goal

- have two seperated layouts: `default.vue` and `mobile.vue`

**Comment by alimuddindqm** [comment]
i have the same issue here, i think because default ssr behavior of nuxt3?

**Comment by JonatasBSM** [comment]
me too

**Comment by JonatasBSM** [comment]
> Could you please try using `<NuxtLayout>` component instead of `definePageMeta` and let me know whether this works for you?
> 
> https://nuxt.com/docs/api/components/nuxt-layout
> 
> ```
> <template>
>   <NuxtLayout :name="device.isMobile ? 'mobile' : 'default'">
>     ...
>   </NuxtLayout>
> </template>
> 
> <script setup>
> const device = useDevice()
> </script>
> ```

worked like a charm! Thank you!

**Comment by DamianGlowala** [comment]
Happy to hear! I'll close the issue.
