### ISSUE TITLE
 Cannot read properties of undefined (reading 'defaultUserAgent')

### ISSUE THREAD

**Issue by hslee2008** [nuxt-modules/device#185]
# Documentation

I followed these two steps from the documentation.

```
yarn add --dev @nuxtjs/device
```

```
{
  modules: [
   '@nuxtjs/device',
  ]
}
```

But, something unexpected happened.

![image](https://github.com/nuxt-modules/device/assets/78584173/4bce2c2c-da1c-44d4-a8c7-b01d9ac6bf39)

![image](https://github.com/nuxt-modules/device/assets/78584173/db55ba3d-55ac-435a-baca-e806f6442fdb)

![image](https://github.com/nuxt-modules/device/assets/78584173/557a0dc5-3a9e-44c9-8689-53a22295d803)

I did try defining defaultUserAgent in `device`, but the error is still there.

**Comment by five1** [comment]
I was getting the same error after installing version 3.2.4 using `npx nuxi@latest module add device`.
Error in console: `[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'defaultUserAgent')`

I no longer get the error after adding a `defaultUserAgent` to my Nuxt config. It seems that the `defaultUserAgent` option is mandatory.
``` js
runtimeConfig: {
    public: {
      device: {
        defaultUserAgent:
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.39 Safari/537.36'
      }
  }
}
```
