### ISSUE TITLE
Running on Nuxt.js head using this.$device.isDesktop

### ISSUE THREAD

**Issue by dyarfi** [nuxt-modules/device#85]
Hi, this is a great module, I try to use and test this on the Nuxt.js `head` using `this.$device.isDesktop`:
```
head() {
   const { $device } = this
   return {
      title: 'page title',
      ...($device.isDesktop && {
        script: [
          {
            innerHTML: 'structuredData',
            type: 'application/ld+json'
          }
        ]
      })
   }
}
```

The module only working on `yarn dev` not on `build` or `generate` even on `yarn start`. Am I missing something? well, my actual target was `$device.isCrawler` to load scripts only on bots engine (Not yet tested on live).

Tested on:
`"nuxt": "^2.14.12"`
`"@nuxtjs/device": "^2.1.0"`

Thank you

**Comment by DamianGlowala** [comment]
As Nuxt 2 has reached End of Life (https://nuxt.com/blog/nuxt2-eol), this issue will now be closed. Please feel free to comment or create a new one if it is still relevant in the Nuxt 3 version of this module.
