### ISSUE TITLE
How does refreshOnResize work?

### ISSUE THREAD

**Issue by IamRaduB** [nuxt-modules/device#90]
Perhaps I misunderstood what refreshOnResize does, but it seems that it just populates the flags again, only taking into account the user agent. The user agent does not change when you resize the browser window or rotate the mobile device, so I dont understand what its purpose is.

**Comment by sioniks** [comment]
Oh, I have the same question. If I open devtools, everything breaks at once.

**Comment by n4ks** [comment]
same, my v-if / v-else doesn't work with refreshOnResize option

**Comment by dotneet** [comment]
The option is the solution for a problem mentioned in the following issue.
https://github.com/nuxt-community/device-module/issues/60#issuecomment-785826433

**Comment by n4ks** [comment]
> > The option is the solution for a problem mentioned in the following issue. [#60 (comment)](https://github.com/nuxt-community/device-module/issues/60#issuecomment-785826433)
> 
> hi, i saw this problem and read the comments. But the Resize option still doesn't work((

You can use the device-type plugin for SSR checks. To check the resize in the browser, you can use the resize event listener + window.innerWidth and additionally check the device type via $device if required.
